// src/components/Sidebar.tsx
import { Bone, BriefcaseMedical, Calendar, ChartSpline, Hotel, LogOutIcon, Table, UserIcon } from "lucide-react"
import { Logo } from "./Logo"
import { ButtonWrapper } from "./ui/ButtonWrapper"
import { NavContainer } from "./ui/NavContainer"
import { useNavigate } from "react-router"

const navItems = [
  { icon: BriefcaseMedical, href: 'emergencias' },
  { icon: Calendar, href: 'citas' },
  { icon: Bone, href: 'nutricion' },
  { icon: Hotel, href: 'hospedaje' },
  { icon: Table, href: 'tablas' },
  { icon: ChartSpline, href: 'finanzas' }
]

export const Sidebar = () => {
  const navigate = useNavigate()

  const handleLogOut = () => {
    alert('Logged out')
    navigate("/")
  }

  return (
    <aside className="h-ful flex flex-col justify-between items-center gap-5 max-w-min">
      <Logo />
      <NavContainer className="grow">
        {
          navItems.map(item => (
            <li>
              <ButtonWrapper
                key={item.href}
                type="link"
                href={item.href}
                replace
                className={({ isActive }) => isActive ? 'text-highlight bg-bg-secondary' : 'text-fg-primary'}
              >
                <item.icon />
              </ButtonWrapper>
            </li>
          ))
        }
      </NavContainer>
      <div className="w-12 p-1.5 min-h-12 bg-white rounded-[176px]">
        <ul className="flex flex-col gap-2">
          <li>
            <ButtonWrapper
              type="link"
              href="user/profile"
              replace
              className={({ isActive }) => isActive ? 'text-highlight bg-bg-secondary' : 'text-fg-primary'}
            >
              <UserIcon />
            </ButtonWrapper>
          </li>
          <li>
            <ButtonWrapper
              type="button"
              className="hover:text-red-600"
              onClick={handleLogOut}
            >
              <LogOutIcon />
            </ButtonWrapper>
          </li >
        </ul >
      </div >
    </aside >
  )
}

// src/app/components/sidebar/sidebar.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { SidebarItemComponent } from '../sidebar item/sidebar item.component';
import { LucideAngularModule, BriefcaseMedical, LogOut, User, Calendar, Bone, Hotel, Table } from "lucide-angular"
import { SidebarButtonComponent } from '../sidebar-button/sidebar-button.component';

@Component({
  selector: 'app-sidebar',
  imports: [SidebarItemComponent, LucideAngularModule, SidebarButtonComponent],
  templateUrl: './sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SidebarComponent {

  LogOutIcon = LogOut;
  UserIcon = User;

  navItems = [
    { icon: BriefcaseMedical, href: '/dashboard/emergencias' },
    // { icon: PawPrint, href: '/dashboard/pets' },
    { icon: Calendar, href: '/dashboard/citas' },
    { icon: Bone, href: '/dashboard/nutricion' },
    { icon: Hotel, href: '/dashboard/hospedaje' },
    { icon: Table, href: '/dashboard/tablas' }
  ];

  logout() {
    alert('Logout');
  }
}
